apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  name: demo-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: arm32v6/nginx:1.17-alpine
          imagePullPolicy: IfNotPresent
          name: web
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always

